# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Cocktail.create(name: "Old Fashioned", description: "delicious")

Ingredient.create(name: "Absinthe")
Ingredient.create(name: "Apple Juice")
Ingredient.create(name: "Bitters - Angostura Aromatic")
Ingredient.create(name: "Brandy")
Ingredient.create(name: "Champagne - Brut")
Ingredient.create(name: "Club Soda")
Ingredient.create(name: "Coffee Liqueur")
Ingredient.create(name: "Cognac V.S.O.P.")
Ingredient.create(name: "Cranberry Juice")
Ingredient.create(name: "Cream")
Ingredient.create(name: "Egg White")
Ingredient.create(name: "Elderflower Liquid")
Ingredient.create(name: "Gin")
Ingredient.create(name: "Gin - London Dry")
Ingredient.create(name: "Grapefruit Juice")
Ingredient.create(name: "Kahlua")
Ingredient.create(name: "Lemon Juice")
Ingredient.create(name: "Lime Juice")
Ingredient.create(name: "Mead")
Ingredient.create(name: "Mint")
Ingredient.create(name: "Mezcal")
Ingredient.create(name: "Orange Juice")
Ingredient.create(name: "Pisco")
Ingredient.create(name: "Pineapple Juice")
Ingredient.create(name: "Pomegranate (grenadine) syrup")
Ingredient.create(name: "Rum - Light White")
Ingredient.create(name: "Sake")
Ingredient.create(name: "Simple Syrup")
Ingredient.create(name: "Tequila")
Ingredient.create(name: "Triple sec liqueur")
Ingredient.create(name: "Vermouth - Dry")
Ingredient.create(name: "Vodka")
Ingredient.create(name: "Whiskey")
Ingredient.create(name: "Whiskey - Blended Scotch")
Ingredient.create(name: "Whiskey - Bourbon")
